# Generated by Django 5.0.6 on 2024-05-30 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements_app', '0001_initial'),
        ('sensor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='sensor_app.sensor'),
        ),
    ]
