# Generated by Django 5.0.6 on 2024-05-30 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponic_system_app', '0006_delete_owner'),
        ('measurements_app', '0002_alter_measurements_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='hydroponic_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hydroponic_system', to='hydroponic_system_app.hydroponicsystem'),
        ),
    ]
