# Generated by Django 5.0.6 on 2024-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements_app', '0006_alter_measurements_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
