# Generated by Django 5.0.6 on 2024-05-29 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponic_system_app', '0002_remove_sensor_ph_remove_sensor_tds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='hydroponic_system',
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
