# Generated by Django 5.0.6 on 2024-05-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponic_system_app', '0005_alter_hydroponicsystem_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
