# Generated by Django 5.0.6 on 2024-06-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponic_system_app', '0007_alter_hydroponicsystem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydroponicsystem',
            options={},
        ),
    ]
