# Generated by Django 5.0.6 on 2024-05-30 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponic_system_app', '0004_alter_hydroponicsystem_owner'),
        ('sensor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='hydroponic_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='hydroponic_system_app.hydroponicsystem'),
        ),
    ]
